version: '3.4'

services:

  api:
    container_name: myfood_api
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    environment:
      JWT_SECRET:
      MONGO_URI:

  mongo:
    container_name: myfood_mongo
    image: mongo:4
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
