version: '3.4'

services:
  api:
    ports:
      - "4000:4000"
    command: npm run dockerdev
    volumes:
      - ./apps/api:/usr/app

  mongo:
    ports:
      - "27017:27017"

  mongo-express:
    container_name: myfood_mongo_express
    image: mongo-express:0.49
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: "myfood_mongo"
